package cmd

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"

	"github.com/jkandasa/containerctl/internal/config"
	rt "github.com/jkandasa/containerctl/internal/runtime"
)

// defaultGenerateProject is used when neither --project nor a loadable stack
// file supplies a project name.
const defaultGenerateProject = "myproject"

// generateHeader is prepended to the rendered YAML. Kept free of timestamps so
// regenerating the same host produces a byte-identical file.
const generateHeader = `# Generated by "containerctl generate" — review before applying.
# Values matching the image defaults are omitted; anonymous volumes are
# emitted as comments; env values are copied verbatim and may contain secrets.
`

var flagGenerateOut string

var generateCmd = &cobra.Command{
	Use:   "generate [name...]",
	Short: "Generate a stack.yaml from running/stopped containers",
	Long: `Generate a stack.yaml from containers that already exist on the host.

With no arguments every container on the host is captured; pass container names
to limit the output. The project name is taken from --project, then from the
project in the current stack file, then defaults to "` + defaultGenerateProject + `".

The result is a starting point, not a byte-exact reproduction: settings that
match the image defaults are omitted, anonymous volumes and unsupported
settings are reported as warnings on stderr, and env values are copied
verbatim — review the file (and its permissions) before applying it.`,
	RunE: runGenerate,
}

func init() {
	generateCmd.Flags().StringVarP(&flagGenerateOut, "out", "O", "", "write output to FILE (created with mode 0600) instead of stdout")
	rootCmd.AddCommand(generateCmd)
}

type generateResult struct {
	container config.Container
	networks  []netRef // networks this container is attached to
	anonVols  []string // anonymous volume strings omitted from the config
	warnings  []string // per-container notes for stderr
}

// netRef pairs the network name written to the YAML with the name it has on the
// host. They differ by the "<project>_" prefix that apply adds back.
type netRef struct {
	logical string
	actual  string
}

func runGenerate(cmd *cobra.Command, args []string) error {
	ctx := context.Background()

	// A stack file is optional here: it only supplies runtime/socket/project
	// defaults when present.
	stack, _ := config.Load(flagFile)

	project := flagProject
	if project == "" && stack != nil {
		project = stack.Project
	}
	if project == "" {
		project = defaultGenerateProject
	}

	client, err := runtimeFromOptional(stack)
	if err != nil {
		return err
	}
	defer client.Close()

	if err := pingRuntime(ctx, client); err != nil {
		return err
	}

	all, err := client.ListContainers(ctx, rt.Filters{})
	if err != nil {
		return err
	}

	candidates, err := selectContainers(all, args)
	if err != nil {
		return err
	}

	var results []generateResult
	for _, c := range candidates {
		info, err := client.InspectContainer(ctx, c.ID)
		if err != nil {
			warnf("inspect %s: %v", c.Name, err)
			continue
		}
		if info == nil {
			continue // removed between list and inspect
		}
		// Missing or unreadable image config only costs us the ability to
		// filter out image defaults, so failures are not fatal.
		imgCfg, _ := client.InspectImageConfig(ctx, info.Image)
		results = append(results, containerInfoToConfig(info, imgCfg, project))
	}
	if len(results) == 0 {
		return fmt.Errorf("no containers to generate from")
	}

	// Stable output: same host state produces the same file.
	sort.Slice(results, func(i, j int) bool {
		return results[i].container.Name < results[j].container.Name
	})
	dedupeContainerNames(results)

	networks, netWarnings := collectNetworks(ctx, client, results, project)

	for _, r := range results {
		for _, w := range r.warnings {
			warnf("%s: %s", r.container.Name, w)
		}
		for _, av := range r.anonVols {
			warnf("%s: anonymous volume omitted (auto-generated by the runtime): %s", r.container.Name, av)
		}
	}
	for _, w := range netWarnings {
		warnf("%s", w)
	}

	containers := make([]config.Container, len(results))
	for i, r := range results {
		containers[i] = r.container
	}

	out := config.Stack{
		Project:    project,
		Networks:   networks,
		Containers: containers,
	}
	// Only record the runtime when it is not the default, so generated files
	// stay portable.
	if name := client.Name(); name != "" && name != "docker" {
		out.Runtime = name
	}

	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(out); err != nil {
		return err
	}
	if err := enc.Close(); err != nil {
		return err
	}

	final := generateHeader + injectAnonVolumeComments(buf.String(), results)

	if flagGenerateOut == "" {
		_, err = io.WriteString(os.Stdout, final)
		return err
	}

	// 0600: generated files routinely contain credentials copied from env.
	f, err := os.OpenFile(flagGenerateOut, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o600)
	if err != nil {
		return fmt.Errorf("create output file: %w", err)
	}
	if _, err := io.WriteString(f, final); err != nil {
		f.Close()
		return fmt.Errorf("write %s: %w", flagGenerateOut, err)
	}
	if err := f.Close(); err != nil {
		return fmt.Errorf("write %s: %w", flagGenerateOut, err)
	}
	return nil
}

func warnf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "WARN: "+format+"\n", args...)
}

// selectContainers filters all by the requested names, erroring on names that
// match nothing so a typo cannot silently produce a partial file.
func selectContainers(all []rt.ContainerInfo, names []string) ([]rt.ContainerInfo, error) {
	if len(names) == 0 {
		return all, nil
	}
	byName := make(map[string]rt.ContainerInfo, len(all))
	for _, c := range all {
		byName[c.Name] = c
	}
	var out []rt.ContainerInfo
	var missing []string
	for _, n := range names {
		c, ok := byName[n]
		if !ok {
			missing = append(missing, n)
			continue
		}
		out = append(out, c)
	}
	if len(missing) > 0 {
		return nil, fmt.Errorf("container(s) not found on host: %s", strings.Join(missing, ", "))
	}
	return out, nil
}

// dedupeContainerNames keeps container names unique — apply rejects duplicates.
// Collisions happen when containers from different projects share a suffix
// (e.g. "web_api" under project "web" and a bare "api").
func dedupeContainerNames(results []generateResult) {
	seen := make(map[string]bool, len(results))
	for i := range results {
		name := results[i].container.Name
		if !seen[name] {
			seen[name] = true
			continue
		}
		unique := name
		for n := 2; seen[unique]; n++ {
			unique = fmt.Sprintf("%s-%d", name, n)
		}
		seen[unique] = true
		results[i].warnings = append(results[i].warnings,
			fmt.Sprintf("duplicate container name %q; renamed to %q", name, unique))
		results[i].container.Name = unique
	}
}

// collectNetworks turns the per-container network references into top-level
// network declarations. Without these, apply has nothing to create and refuses
// to attach containers.
func collectNetworks(ctx context.Context, client rt.Runtime, results []generateResult, project string) ([]config.Network, []string) {
	drivers := map[string]string{}
	if nets, err := client.ListNetworks(ctx, rt.Filters{}); err == nil {
		for _, n := range nets {
			drivers[n.Name] = n.Driver
		}
	}

	byLogical := map[string]netRef{}
	var warnings []string
	for _, r := range results {
		for _, ref := range r.networks {
			prev, ok := byLogical[ref.logical]
			if !ok {
				byLogical[ref.logical] = ref
				continue
			}
			if prev.actual != ref.actual {
				warnings = append(warnings, fmt.Sprintf(
					"networks %q and %q both map to %q; only %q is declared",
					prev.actual, ref.actual, ref.logical, prev.actual))
			}
		}
	}

	logicalNames := make([]string, 0, len(byLogical))
	for l := range byLogical {
		logicalNames = append(logicalNames, l)
	}
	sort.Strings(logicalNames)

	out := make([]config.Network, 0, len(logicalNames))
	for _, l := range logicalNames {
		ref := byLogical[l]
		n := config.Network{Name: l}
		// "bridge" is the default applied on load; omit it to reduce noise.
		if d := drivers[ref.actual]; d != "" && d != "bridge" {
			n.Driver = d
		}
		out = append(out, n)
		if ref.actual != config.NetworkFullName(project, l) {
			warnings = append(warnings, fmt.Sprintf(
				"network %q is not owned by project %q: apply will create %q and attach containers to it instead",
				ref.actual, project, config.NetworkFullName(project, l)))
		}
	}
	if len(out) == 0 {
		return nil, warnings
	}
	return out, warnings
}

// injectAnonVolumeComments does a line-by-line pass over the rendered YAML and
// inserts commented-out anonymous volume entries at the end of each container
// block that had anonymous volumes.  With SetIndent(2), container list items
// always start with "  - name: <name>", so boundaries are unambiguous.
func injectAnonVolumeComments(yamlStr string, results []generateResult) string {
	anonByName := make(map[string][]string, len(results))
	for _, r := range results {
		if len(r.anonVols) > 0 {
			anonByName[r.container.Name] = r.anonVols
		}
	}
	if len(anonByName) == 0 {
		return yamlStr
	}

	lines := strings.Split(strings.TrimRight(yamlStr, "\n"), "\n")
	out := make([]string, 0, len(lines)+len(anonByName)*3)

	inContainers := false
	currentName := ""

	flush := func() {
		if currentName == "" {
			return
		}
		if avols, ok := anonByName[currentName]; ok {
			out = append(out, "    # Anonymous volumes (auto-generated by the runtime) - replace with explicit paths:")
			for _, av := range avols {
				out = append(out, "    # - "+av)
			}
		}
		currentName = ""
	}

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		if trimmed == "containers:" {
			flush()
			inContainers = true
			out = append(out, line)
			continue
		}

		// A non-indented non-empty line means we left the containers section.
		if inContainers && len(line) > 0 && line[0] != ' ' {
			flush()
			inContainers = false
		}

		// Each container list item starts with "  - name: <name>" (SetIndent(2)).
		if inContainers && strings.HasPrefix(line, "  - ") {
			flush()
			if rest := strings.TrimPrefix(line, "  - "); strings.HasPrefix(rest, "name: ") {
				currentName = strings.TrimSpace(strings.TrimPrefix(rest, "name: "))
			}
		}

		out = append(out, line)
	}

	flush() // handle the last container
	return strings.Join(out, "\n") + "\n"
}

func containerInfoToConfig(info *rt.ContainerInfo, imgCfg *rt.ImageConfig, project string) generateResult {
	res := generateResult{}

	// Containers created by containerctl carry their logical name as a label;
	// for everything else fall back to trimming the project prefix.
	name := info.Labels[rt.LabelName]
	if name == "" {
		name = strings.TrimPrefix(strings.TrimPrefix(info.Name, "/"), project+"_")
	}

	// Build map of image-default env so we can filter them out.
	imgEnv := make(map[string]string)
	if imgCfg != nil {
		for _, kv := range imgCfg.Env {
			k, v, _ := strings.Cut(kv, "=")
			imgEnv[k] = v
		}
	}
	var env map[string]string
	for _, kv := range info.Env {
		k, v, _ := strings.Cut(kv, "=")
		if def, ok := imgEnv[k]; ok && def == v {
			continue // same as image default, omit
		}
		if env == nil {
			env = make(map[string]string)
		}
		env[k] = v
	}

	var imgCmd, imgEntrypoint []string
	var imgHealthcheck *rt.Healthcheck
	imgUser, imgWorkingDir := "", ""
	if imgCfg != nil {
		imgCmd, imgEntrypoint = imgCfg.Cmd, imgCfg.Entrypoint
		imgHealthcheck = imgCfg.Healthcheck
		imgUser, imgWorkingDir = imgCfg.User, imgCfg.WorkingDir
	}

	var command []string
	if !strSlicesEqual(info.Command, imgCmd) {
		command = nilIfEmpty(info.Command)
	}

	var entrypoint []string
	if !strSlicesEqual(info.Entrypoint, imgEntrypoint) {
		entrypoint = nilIfEmpty(info.Entrypoint)
	}

	restart := info.RestartPolicy
	if restart == "no" {
		restart = ""
	}

	var ports []string
	for _, p := range sortPortBindings(info.Ports) {
		if p.HostPort == "" {
			// Exposed-only: mostly the image's own EXPOSE list, and a config
			// entry without a host port would publish on a random port.
			continue
		}
		ports = append(ports, formatPortBinding(p))
	}

	var volumes []string
	for _, m := range sortMounts(info.Mounts) {
		if m.Type == "tmpfs" {
			continue // reported separately via HostConfig.Tmpfs
		}
		source := m.Source
		if m.Type == "volume" {
			if isAnonymousVolume(m.Name) {
				res.anonVols = append(res.anonVols, m.Name+":"+m.Destination)
				continue
			}
			source = m.Name
		}
		s := source + ":" + m.Destination
		if m.ReadOnly {
			s += ":ro"
		}
		volumes = append(volumes, s)
	}

	// Networks are declared with the project prefix stripped; apply adds it
	// back. Built-in networks are not user-defined and cannot be declared.
	netNames := make([]string, 0, len(info.NetworkInfos))
	for _, n := range info.NetworkInfos {
		netNames = append(netNames, n.Name)
	}
	sort.Strings(netNames)

	var networks []string
	for _, n := range netNames {
		switch n {
		case "bridge":
			continue // the default network apply also lands on
		case "host", "none":
			res.warnings = append(res.warnings, fmt.Sprintf(
				"network mode %q is not supported: the generated container will use the default bridge", n))
			continue
		}
		logical := strings.TrimPrefix(n, project+"_")
		networks = append(networks, logical)
		res.networks = append(res.networks, netRef{logical: logical, actual: n})
	}

	// Aliases the runtime adds by itself (name, hostname, short ID) are not
	// user configuration.
	var networkAliases []string
	seenAlias := map[string]bool{
		name:          true,
		info.Name:     true,
		info.Hostname: true,
	}
	if len(info.ID) >= 12 {
		seenAlias[info.ID[:12]] = true
	}
	for _, n := range netNames {
		for _, a := range info.NetworkAliases[n] {
			if seenAlias[a] {
				continue
			}
			seenAlias[a] = true
			networkAliases = append(networkAliases, a)
		}
	}

	var labels map[string]string
	for k, v := range info.Labels {
		// containerctl.* is bookkeeping apply rewrites itself, and compose
		// labels would make docker compose believe it still owns the container.
		if strings.HasPrefix(k, "containerctl.") || strings.HasPrefix(k, "com.docker.compose.") {
			continue
		}
		if imgCfg != nil && imgCfg.Labels[k] == v {
			continue // image-default label, not user-set
		}
		if labels == nil {
			labels = make(map[string]string)
		}
		labels[k] = v
	}

	var resources config.Resources
	if info.Resources.NanoCPUs > 0 {
		resources.CPUs = strconv.FormatFloat(float64(info.Resources.NanoCPUs)/1e9, 'f', -1, 64)
	}
	if info.Resources.MemoryBytes > 0 {
		resources.Memory = formatMemoryBytes(info.Resources.MemoryBytes)
	}
	resources.PidsLimit = info.Resources.PidsLimit

	var healthcheck *config.Healthcheck
	if info.Healthcheck != nil && !healthcheckEqual(info.Healthcheck, imgHealthcheck) {
		healthcheck = &config.Healthcheck{
			Test:     info.Healthcheck.Test,
			Interval: durationString(info.Healthcheck.Interval),
			Timeout:  durationString(info.Healthcheck.Timeout),
			Start:    durationString(info.Healthcheck.StartPeriod),
			Retries:  info.Healthcheck.Retries,
		}
	}

	// User/WorkingDir: omit when they match the image default.
	user := info.User
	if user == imgUser {
		user = ""
	}
	workingDir := info.WorkingDir
	if workingDir == imgWorkingDir {
		workingDir = ""
	}

	// Hostname: omit when it is either the runtime default (first 12 chars of
	// the container ID) or the value apply would derive from the name anyway.
	hostname := info.Hostname
	if hostname == name || (len(info.ID) >= 12 && hostname == info.ID[:12]) {
		hostname = ""
	}

	res.container = config.Container{
		Name:           name,
		Image:          info.Image,
		Env:            env,
		Command:        command,
		Entrypoint:     entrypoint,
		Restart:        restart,
		Ports:          nilIfEmpty(ports),
		Volumes:        nilIfEmpty(volumes),
		Networks:       nilIfEmpty(networks),
		NetworkAliases: nilIfEmpty(networkAliases),
		Labels:         labels,
		Resources:      resources,
		Healthcheck:    healthcheck,
		User:           user,
		WorkingDir:     workingDir,
		Hostname:       hostname,
		DNS:            nilIfEmpty(info.DNS),
		GroupAdd:       nilIfEmpty(info.GroupAdd),
		CapAdd:         nilIfEmpty(info.CapAdd),
		CapDrop:        nilIfEmpty(info.CapDrop),
		Privileged:     info.Privileged,
		SecurityOpt:    nilIfEmpty(info.SecurityOpt),
		ReadOnly:       info.ReadOnly,
		Tmpfs:          nilIfEmpty(sortedCopy(info.Tmpfs)),
	}
	return res
}

// isAnonymousVolume reports whether name is a runtime-generated anonymous
// volume ID (64-character lowercase hex string).
func isAnonymousVolume(name string) bool {
	if len(name) != 64 {
		return false
	}
	for _, c := range name {
		if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f')) {
			return false
		}
	}
	return true
}

// sortMounts orders mounts by destination so the generated file does not churn
// between runs — the runtime does not report them in a stable order.
func sortMounts(mounts []rt.ContainerMount) []rt.ContainerMount {
	out := make([]rt.ContainerMount, len(mounts))
	copy(out, mounts)
	sort.Slice(out, func(i, j int) bool {
		if out[i].Destination != out[j].Destination {
			return out[i].Destination < out[j].Destination
		}
		return out[i].Source < out[j].Source
	})
	return out
}

// sortPortBindings orders bindings by container port, then protocol, then host
// port so the generated file does not churn between runs (the runtime reports
// bindings from a map).
func sortPortBindings(ports []rt.PortBinding) []rt.PortBinding {
	out := make([]rt.PortBinding, len(ports))
	copy(out, ports)
	sort.Slice(out, func(i, j int) bool {
		a, b := out[i], out[j]
		if ai, bi := portNum(a.ContainerPort), portNum(b.ContainerPort); ai != bi {
			return ai < bi
		}
		if a.Protocol != b.Protocol {
			return a.Protocol < b.Protocol
		}
		if ai, bi := portNum(a.HostPort), portNum(b.HostPort); ai != bi {
			return ai < bi
		}
		return a.HostIP < b.HostIP
	})
	return out
}

func portNum(s string) int {
	n, err := strconv.Atoi(s)
	if err != nil {
		return 0
	}
	return n
}

func formatPortBinding(p rt.PortBinding) string {
	var sb strings.Builder
	if p.HostPort != "" {
		if p.HostIP != "" {
			sb.WriteString(p.HostIP)
			sb.WriteByte(':')
		}
		sb.WriteString(p.HostPort)
		sb.WriteByte(':')
	}
	sb.WriteString(p.ContainerPort)
	if p.Protocol != "" && p.Protocol != "tcp" {
		sb.WriteByte('/')
		sb.WriteString(p.Protocol)
	}
	return sb.String()
}

func formatMemoryBytes(bytes int64) string {
	const (
		gig  = 1024 * 1024 * 1024
		mega = 1024 * 1024
		kilo = 1024
	)
	switch {
	case bytes%gig == 0:
		return fmt.Sprintf("%dg", bytes/gig)
	case bytes%mega == 0:
		return fmt.Sprintf("%dm", bytes/mega)
	case bytes%kilo == 0:
		return fmt.Sprintf("%dk", bytes/kilo)
	default:
		return fmt.Sprintf("%db", bytes)
	}
}

func durationString(d time.Duration) string {
	if d == 0 {
		return ""
	}
	return d.String()
}

func nilIfEmpty(s []string) []string {
	if len(s) == 0 {
		return nil
	}
	return s
}

func sortedCopy(s []string) []string {
	out := make([]string, len(s))
	copy(out, s)
	sort.Strings(out)
	return out
}

func strSlicesEqual(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func healthcheckEqual(a, b *rt.Healthcheck) bool {
	if a == nil || b == nil {
		return a == b
	}
	return strSlicesEqual(a.Test, b.Test) &&
		a.Interval == b.Interval &&
		a.Timeout == b.Timeout &&
		a.StartPeriod == b.StartPeriod &&
		a.Retries == b.Retries
}
